### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by binji** [WebAssembly/threads#10]
We rely on the spec conformance test suite to help ensure consistent behavior across WebAssembly implementations. How should we test the behavior of the atomic operations? The [ECMAScript tests](https://github.com/tc39/test262/tree/master/test/built-ins) are primarily API tests, though there are some that require the harness to provide a mechanism for spawning new threads and sending messages between them.

What tests will we want for WebAssembly?

**Comment by lars-t-hansen** [comment]
The ES tests pretty much assume that atomicity is properly implemented, and then test wait/wake and memory sharing, in addition to pure API tests.   The latter groups carry over easily to wasm I should think.

Testing fences, and what compilers and hardware do with ordering constraints (notably on ARM), is probably more interesting than testing access-atomicity per se.  (Also easier to test properly for wasm than for ES, since the ES tests tend to run in the interpreter.)

**Comment by binji** [comment]
We agreed in the CG meeting to provide API coverage and basic threading interaction, similar to what's currently provided by test262 for SABs. There was weak agreement to provide litmus tests for v1 threads (similar to work provided by https://github.com/FMJS/EMME).
