### ISSUE TITLE
Is the set of proposed instructions sufficient?

### ISSUE THREAD

**Issue by binji** [WebAssembly/threads#11]
The current proposal doesn't have much more than what is currently in ES. Do we want other instructions?

**Comment by lars-t-hansen** [comment]
One operation that never made it into ES was an instruction to relax in a spinloop (ie, the PAUSE instruction in x86, IIRC).  It was in the very earliest drafts of the spec but I think that, more than anything, it was considered very low-level for ES and something that would create controversy.    (I experimented with a related idea, a micro-wait primitive with a back-off scheme, and I called that "pause" too, but it's not what I'm talking about here.)

I know that PAUSE is important for performance on x86.  I don't know if ARM has anything similar in eg its event instructions (WFE).  I don't know if it's a good idea to push this through for the MVP since we won't be able to remove it again if it turns out to be the wrong thing.

**Comment by jfbastien** [comment]
Worth forking as a separate question, and polling (ha!) at the upcoming meeting.

**Comment by binji** [comment]
There wasn't a poll about this in the CG meeting, but there seemed to be interest in exploring adding a `yield` operation (as opposed to `pause`). This would be defined in the spec as being a no-op, but would be a hint to implementations to yield execution to another thread.

**Comment by binji** [comment]
As for other operations, we discussed other atomic primitives, including:

* neg
* min/max
* signed/unsigned (this is in the notes, but I can't recall what this means...)
* nand

We decided (without polling) that these other operations could be handled later if there is interest.
