### ISSUE TITLE
Memory ordering - Sequential Consistency only?

### ISSUE THREAD

**Issue by binji** [WebAssembly/threads#13]
The current proposal only allows for sequentially consistent memory ordering. How will we want to support other memory orderings (i.e. what is the encoding)? Do we want to support other orderings for the initial version?

**Comment by lars-t-hansen** [comment]
I should know the answer to this, but I don't think I do: Suppose I have a wasm program that uses weak atomic operations (weaker than seq_cst), but my compiler treats every atomic operation as seq_cst, will the compiler be correct?

(The question is interesting both because I wonder whether the weaker operations can be promoted so that I can write a working compiler more quickly, and because I wonder whether wasm must provide the weaker operations to be viable as a C++ target.  Either way I hope the answer to my question is "yes".)

**Comment by jfbastien** [comment]
For C++, yes. The model is SC-DRF, so making everything (even non-atomic) SC keeps that property as long as DRF.

**Comment by binji** [comment]
We agreed in the CG meeting to provide only sequentially-consistent atomics for v1 threads.
