### ISSUE TITLE
two threads of one module share the global variables or not?

### ISSUE THREAD

**Issue by xwang98** [WebAssembly/threads#156]
In the C programming, two threads spawned from the same code expect to share the global variables. I wonder if two threads (with associated instances) created from the same WASM module should share the globals (less the mutable ones) by default?

**Comment by tlively** [comment]
No, WebAssembly globals are not shared between instances and therefore are not shared between threads. That being said, global variables in source level languages are typically placed in a shared memory rather than in WebAssembly globals, so your source-level globals will be shared between threads.

**Comment by xwang98** [comment]
@tlively I have just done a small expriment. Yes you are right. Thanks!

**Comment by xwang98** [comment]
@tlively I just had a second thought about it. What you said implies  the WASM compiler must not use the WASM globals for the global variables in the source level lanaguages.  I believe it is how LLVM is implemented for WASM backend, but not sure if some other compilers like asmblyScript have followed this rule. 

If it is right, maybe we should make it explicitly stated somewhere?

**Comment by xwang98** [comment]
@binji @tlively  we are working on an experimental compiler to convert some domain language to WASM, which is based on Binaryen rather than LLVM. It seems we have to move the global variables from WASM globals to linear memory for sharing between threads, then we have to manually layout the linear memory for global variables.

I am not very sure about what I said previously:
>  I believe it is how LLVM is implemented for WASM backend
Is it done by clang front end or the llvm backend? I wonder if we can get rid of this problem by switching to llvm.

copy @xujuntwt95329

**Comment by Pauan** [comment]
@xwang98 I would just like to note that [Rust uses Wasm globals](https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html) in order to get per-thread IDs (which is necessary for thread local data to work). So there are use cases for Wasm globals *not* being shared.

(Incidentally, global variables in Rust are put into Wasm linear memory, not Wasm globals, so Wasm globals are an internal detail used only for threads.)

**Comment by tlively** [comment]
Yes, LLVM will take care of placing global variables in memory. On the other hand, LLVM and Binaryen are very different and you should probably not choose to use LLVM only because it will place your globals in memory for you.

@Pauan this probably isn't the best place to discuss this, but I am surprised that Rust does anything with wasm globals directly. Wouldn't it be cleaner to use LLVM's thread local storage support?

**Comment by Pauan** [comment]
@tlively rustc doesn't have any support at all for multithreading on Wasm (it does not use Wasm globals). The support for multithreading comes from wasm-bindgen.

wasm-bindgen [does indeed use LLVM's local thread support](https://github.com/rustwasm/wasm-bindgen/commit/8cb792474cedbfb8d2e7e3c1c38fc2df4cdabca1), the article I linked to is out of date (though the same principle applies, since LLVM uses a Wasm global for thread locals).
