### ISSUE TITLE
Import semantics of shared vs non-shared memories

### ISSUE THREAD

**Issue by rossberg-chromium** [WebAssembly/threads#17]
Is there any form of non-trivial subtype relation on the sharing attribute? I suppose it is illegal to supply a shared memory for a memory import that is declared as unshared.

But what about the inverse? Can an unshared memory be supplied for a memory import declared as shared?

**Comment by lars-t-hansen** [comment]
For ES we decided the memories are disjoint: atomics require shared memory, and the spec calls for a dynamic type check that the memory is in fact shared.  Partly this was done because the check is needed anyway, for some implementations of non-lock-free atomics and wait/wake that attach information to the SAB.  For asm.js in particular ISTR we wanted to depend on that, so asm.js performs the "is shared memory" check early, and can then generate code that assumes that.  I suspect we'd prefer to do the same for wasm.

**Comment by lukewagner** [comment]
+1 for no subtyping either way.  This also avoids fun questions like: is `wait` on a non-shared memory simply an automatic deadlock?

**Comment by binji** [comment]
The current proposal has wording to this effect:
```
It is a validation error to attempt to import shared linear memory
if the module's memory import doesn't specify that it allows shared memory.
Similarly, it is a validation error to import non-shared memory if the
module's memory import specifies it as being shared.
```

**Comment by rossberg-chromium** [comment]
Ah, okay. Thanks!
