### ISSUE TITLE
How to pass Wasm SAB to other thread(s)?

### ISSUE THREAD

**Issue by 00ff0000red** [WebAssembly/threads#172]
In a web embedding, as `WebAssembly.Memory` isn't serializable, how does one pass it to, say, another web `Worker`?

Instantiating a module more than once allocates new memory for each instance, so I'm not getting how memory is supposed to be linked across modules.

Yet, plenty of people have supposably been making use of Wasm threads already, ex: experimental Chromium flags and early runtime support. Can someone please point out the appropriate part of the proposal that might help clarify this?

**Comment by dschuff** [comment]
Instantiating a module more than once does not allocate a new memory if the memory is imported (rather than defined by the module itself).
In emscripten, we instantiate a wasm memory, and then instantiate the module with the memory as an import (currently we do this even when when running without threads/SAB). Then for threads, we `postMessage` the module (which is serializable) across to the worker, and instantiate the module again.

**Comment by 00ff0000red** [comment]
> Instantiating a module more than once does not allocate a new memory if the memory is imported (rather than defined by the module itself).

I was about to suggest just that, an opt-in so that the Wasm can remain self-contained, not having to export/import its memory in order to use shared memory, that all instances share the same cached memory.

> In emscripten, we instantiate a wasm memory, and then instantiate the module with the memory as an import (currently we do this even when when running without threads/SAB). Then for threads, we `postMessage` the module (which is serializable) across to the worker, and instantiate the module again.

Once sent to the worker, a new wasm memory needs to be allocated in that thread, so you gain nothing from using shared memory at all, since you can't send that shared memory (not serializable) to the worker. Unless I'm missing a key piece of information here?

**Comment by conrad-watt** [comment]
Communication of objects between Web workers is defined through the  [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm). In the case of a Wasm shared memory, the `buffer` internal property of the memory object is shared between all copies, so postMessage of a shared Wasm memory should just work. 

I don't know what happens when you try to postMessage a non-shared memory, but could this be the source of your expectation that Wasm memories aren't "serializable"?

**Comment by 00ff0000red** [comment]
I have no clue what I am saying, I *know* that I've used experimental multi-threaded Wasm in Chrome before.
Just tested right now, it is serializable, just like `SharedArrayBuffer`, I must've forgotten.

Also, I thought that structured cloning doesn't apply to items that aren't cloned, ex: moving+detaching array buffer or passing sharedarraybuffer?

Well, thank you for provoking my realization, solved the issue.
