### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/threads#182]
When the functions are immutable and their identity is not directly observable by wasm, why are they not part of the shared store, but are in the local store? If no functions are expected to be added/edited/deleted at runtime I see no reason they to be duplicated per thread. Clearly the globals and the tables are the tread local storage at this time.

**Comment by rossberg** [comment]
Functions are essentially closures over the local store, so are tied to it.

**Comment by verbessern** [comment]
What is the rationale about that? Would that make a thread incredibly slow to start? I'm aware that that is how the "biggest client" (JS) does its work, but why that should be the future of the threading? If the functions are moved to the shared store, that will allow an implementation (including JS) to share them. A particular implementation must to corrupt the future of threading, I think at least.

**Comment by rossberg** [comment]
Functions can freely access non-shared memories, globals, and tables from the local store. So they obviously can't be shared themselves – that would indirectly share everything they access, i.e., all accesses to non-shared things would become unsafe.

See Appendix A of our [OOPSLA paper](https://github.com/WebAssembly/spec/blob/master/papers/oopsla2019.pdf) for how the Wasm type system would have to be extended to support (explicitly) shared functions. In particular, a function declared shared must be prohibited from referencing any non-shared entity.

**Comment by verbessern** [comment]
For me the other is obvious, that a function have no need to be a closure at all. It looks to me that this is unnecessary constraint over the functions. 

For me its clear that the store, a function accesses, can easily be done by the use of a thread local variable, and that will decouple the functions from the local store. To avoid this indirection, you force an inlining of all functions per thread, to directly reference the globals and tables in their, lets say, CPU assembly instructions. 

The saving of this one indirection, burdens the thread creation (and deletion, even if GC exists for this). I will take a look on this link, but the basic assumption that the functions are closures is the problem (at least as it seems to me at this point), not how you work with it.

**Comment by rossberg** [comment]
I don't know what you mean. Are you suggesting that all memories and tables should also be thread-local storage? What about globals that contain references to local things? Should there somehow be an implicit deep copy of all these things and the entire local state graph the first time a new thread enters a function?

**Comment by verbessern** [comment]
I have said nothing about that. Neither, for the tables nor globals (that are already thread local anyway). I'm talking about the functions. The functions themself have no data inside, they only reference it, when they reference the local storage, they should do that in a with thread local storage, as any other computer program that works with threads and has local data.

One local variable would even be enough, to just point to the local storage instance, but I see no problem to have each global or table in the thread local storage (as separate variables) as well, as far as their number does not change (as it is at this point in time).

A thread entering a function has to do exactly nothing. Each CPU instruction will use the thread local storage variable to the local store and do its business. This function can be shared across threads. I find it incredible to require that all functions are recompiled or at least patched, for each thread that starts. This can be in megabytes of data dragged around all the time for thread intensive tasks.

**Comment by rossberg** [comment]
I still don't understand what you are suggesting. The local storage can be arbitrarily large, gigabytes of local linear memory, for example, that a function can access. Are you suggesting that each thread holds a thread-local copy of that? If not, what are you suggesting?

> when they reference the local storage, they should do that with thread local variable

I really don't know what that is supposed to mean in the context of Wasm. If I have a function that does, say, a table.set on a non-shared table, then what happens if I call that function in multiple threads?

**Comment by verbessern** [comment]
C++ like:
thread_local store *local_store; // that goes into the PE thread local section 
local_store->tables[0]->set(index, data);

**Comment by rossberg** [comment]
That does not answer my question. Concretely, what would happen here, if it was allowed:
```
(module $LocalTable
    (table 1000 anyref)  ;; not shared
    (func (export "get") (result anyref) (table.get (i32.const 0)))
    (func (export "set") (param $x anyref) (table.set (i32.const 0) (local.get $x)))
)

;; pseudo code
(thread $T1
  (invoke $LocalTable "set" (ref.extern 1))
)

(thread $T2
  (invoke $LocalTable "set" (ref.extern 2))
)

(thread $T3
  (invoke $LocalTable "get") ;; ?
)
```

**Comment by rossberg** [comment]
Functions are closures because that's what Wasm's semantic prescribes: each instantiation of the same module has to produce a new set of exported functions, which use the internals of the respective instance of the module. Technically this means that each function closes over its module instance. There is no way around that.

According to your explanation, there would have to be four copies of the local store, one for each thread (including the main thread). As I said, the local store can be arbitrarily huge (e.g., consist of arbitrarily many module instances, with many large memories or tables), so creating one copy per thread is prohibitive. Also, when do you create these copies? Each time a $Ti is spawned, does it clone the entire local store of the main thread? Or does it create new uninitialised memory/table/global instances for all of them implicitly? I can't think of any affordable and semantically coherent way to define this.

**Comment by verbessern** [comment]
That is circular dependency. You define it to be closure, then you said its closure because "its defined" to be such. The exported functions per module are still the same. 

That is not what I'm saying. Its actually what you are saying. You say that each thread has a local store that includes all memories globals, tables and functions (one of each **per** thread). I'm saying that the functions does not need to be there, because they can be shared easily with the help of TLS as any other threaded program does it.

You want to instantiate everything per thread, every time, I say to instantiate **less** then that, by making the functions **shared** and make them use the TLS to access the local of the thread memories, tables and globals. I do **not** propose to use more memory, you do.  

There is **no** cloning, every local store is unique per thread, as it is **now**. At the thread startup its local store is initialized (as it is now).

**Comment by verbessern** [comment]
This what you have described is **not** multi threading, this **is** multi processing with shared memories.

If you want multi threading you must (RFC 2119) decouple the functions from the instance. Each local to the thread store must be local to it only. If there are no shared objects, they must be there. All shared objects must be in a shared store. The indexing of the store objects in relation to each other must be defined. 

Then one module can be instantiated one time per **process**, then the main thread stared with its local store and the shared store, that should form one "super store" or what ever to call it, where the indexing for the objects is defined. Each new thread does not start as a new process (as it seems you see it now) by initializing all functions, but reuse the existing instance, just create its own local store.

**Comment by conrad-watt** [comment]
We certainly _want_ multithreading as you describe it, but we'll be exploring it as a post-MVP feature. Right now the focus is, as you say, purely on facilitating shared memory concurrency. One could imagine renaming this proposal to "shared memory concurrency" (I'm not sure this is worth the effort), but I think your other recommendations are just out of scope for now.

**Comment by verbessern** [comment]
As a side observer of your work, it seems to me that this is doable and for the MVP, because this is related to how the stores are defined, it does not force the implementations to do any changes, but at least officially allows them to implement their store related code in a way to handle properly the future. For the protocol, I disagree strongly that the functions are closures. 

Thank you for the chat, should I let the thread opened, and if so, should I rename it to something else for a future reference?

**Comment by rossberg** [comment]
It's not how I'm defining it but how Wasm has been designed from the very beginning. It's how module instantiation works, and it's the only way it can reasonably work. How else would you provide the ability to instantiate the same module multiple times? This is completely independent of threading, FWIW.

> TLS to access the local of the thread memories, tables and globals. I do not propose to use more memory, you do.
>
> There is no cloning, every local store is unique per thread, as it is now. At the thread startup its local store is initialized (as it is now).

In your earlier explanation of my example, you said yourself that each thread would access its own, separate table. I can construct the same example with memories. So according to your own explanation, every thread has to have its own copy of all tables and memories it might possibly access. These are all part of its local store! So I still don't understand how to square up what you're saying. Simple question: are there per-thread copies of everything now or aren't there?

**Comment by verbessern** [comment]
It seems @conrad-watt understood me. I have been consistent in my statements. At the moment all local stores exists per thread. That means that you (=WASM designers) create all memories, tables and globals per thread. I said to exclude the functions from this list, and create less objects. That means less memory. Maybe @conrad-watt  can use better words, in the terminology you often use between each other.

**Comment by rossberg** [comment]
Instead of having others second-guess what you really mean, why not answer the simple question?

**Comment by conrad-watt** [comment]
> As a side observer of your work, it seems to me that this is doable and for the MVP

Just to throw up a few complicating issues, functions with a "shared instance" likely would have to be prevented from calling into JavaScript. We'd also have to come up with a design for how Wasm threads are spawned, while right now we're delegating that part of the design to the host (e.g. the Web Worker API). It's doable, just much more design space than the current MVP.

> Maybe @conrad-watt can use better words, in the terminology you often use between each other.

I think your core ask here is for a Wasm-level mechanism that works like `fork`, allowing both threads access to the same globals/memories/tables without needing to instantiate twice in two separate threads/processes/Web workers, as must be done now.

> It seems @conrad-watt understood me. I have been consistent in my statements.

I've been skipping over the details in the thread discussing how your desired mechanism might be formalised because I think they're secondary to explaining _why_ we're currently not pursuing this approach. I think your question would have been more understandable without these details (and even now, I may have misunderstood!).

**Comment by verbessern** [comment]
Yes there are, because its designed to be. That is what I'm saying in every single post.

**Comment by verbessern** [comment]
@conrad-watt  The question without details is, "why are the functions closures?", but it did not work, so we had to write a chapter of a book. @conrad-watt My question is why the Thread Local Storage (TLS; executables) is not used (thread_local in C++) to store (for example) the local store, so each thread can access it. That will allow the functions to shared. Do you understand that?

**Comment by conrad-watt** [comment]
The instance which a function closure closes over essentially _is_ the per-thread indirection you're proposing (and also allows multiple instantiations in the _same_ thread to share the same compiled code). Maybe it would help to analogise things to C++:

Right now, you can think of _every_ piece of module-level state in Wasm as being `thread_local`, because you can `postMessage` a compiled Wasm module between Web Workers and instantiate it multiple times. So the compiled code of each function is "shared" in the sense you mean (all threads can reference the same copy), while a new copy of the declared module-level state is made each instantiation (somewhat like `thread_local`) which the compiled code references indirectly depending on the current thread executing.

This proposal allows memories to be `shared`, meaning that the same memory can be referenced across instantiations in different threads (closer in spirit to C++ `static`, although with more explicit control). As a post-MVP matter, we will look at other module-level state becoming `shared`.

Allowing a function closure to be shared is a different (and more complicated) design question, compared to allowing the compiled code of the function to be shared between threads (which can already be done today).

**Comment by verbessern** [comment]
@conrad-watt That is all very nice, but its still not it. The proposal (as I interpret it) allows memories to be `shared` not only between instantiations, but generally between the instantiations of different modules (or the same module **copied** into the different Web Workers). 

However, after your explanation, I see that there are 2 stages: 
1) the copies of compiled functions between the Web Workers; and 
2) the module-level function pointers to the already copied compiled function. 

My focus was on the first copies, because, as I understood it, they reference the globals/tables/memories **directly**. For this reason they must be **cloned** per thread, because the thread has this globals/tables/memories only for it self (locals). However, if the instances are already doing this indirection, and the functions are "only" a list of pointers (so to say), then the overhead is not that big (still not zero). 

The same principle could be used to share the functions and across copies, because they are **indirectly** using (as I was trying to vote strongly for) the local per thread globals/tables/memories. 

From the reading of the standard, this it does not get clear for me **at all**. For me by reading "the functions are in the local store" its quite clear that they are **directly** using each global/table/memory (locals). 

If one is implementing the standard, it is **seriously** advisable (as for any other standard) that one implements it strictly "as is", and not assume anything. For this reason, I (or others) cannot (should not) assume that such a sharing exists, because one day you may add other functionalities that rely on this **direct** referencing (as the specs prescribe it = functions are local to the thread), and will break the project. I hope you understand my concerns, and why I debate on it (maybe even (partly) with an annoying persistence).

**Comment by conrad-watt** [comment]
The Wasm standard certainly can't be read as a guide for implementation techniques (with or without this proposal), and I'd say the same for the C++ and JavaScript language standards. That being said, Web engines would likely (and completely reasonably) vote down any change to the Wasm standard that would force them to completely re-engineer their compilation model. One reason we have so many stages of standardisation, and require multiple implementations prior to full standardisation, is to stop this from happening accidentally.

**Comment by verbessern** [comment]
A standard might not be a guide for implementation techniques (at least, because there are no techniques described inside), but certainly is prescribing that final outcome of the implementation, and by this limits/narrows the efficient implementation techniques.

**Comment by verbessern** [comment]
Another thing is that, the Web engines know more then I do (by only reading the standard as PDF). For this reason the developers develop in away, that after the "future" comes (that I have no knowledge about), the changes will be developed with a "reasonable" effort. The Web engine developer knows that this function can be shared like that, but I (and many others) do not. I cannot assume it, because each assumption pushes the project one step to its end (or at best, its temporal stall).

**Comment by verbessern** [comment]
And last but not least, "if one have to read the source code then the documentation is not fine".
