### ISSUE TITLE
Dealing with concurrency between memory accesses and grow relocating memory

### ISSUE THREAD

**Issue by anuraaga** [WebAssembly/threads#203]
This is more of a question for experts than an issue, let me know if there's a better location for it.

I have been implementing the threads proposal for arm64 with wazero and things generally work OK, but only if I preallocate enough memory before beginning concurrent operations. Without doing so, concurrent execution of `memory.grow` and memory accesses causes issues, mainly because to preserve having a linear segment of memory, the memory may be relocated - concurrency between relocation and memory accesses can have those be served from the old memory location, causing corruption. Note that this isn't only ordering as at least on arm64, I don't think it's possible to resolve the memory address in the atomic instruction itself since it doesn't support indexing, there will be two instructions, one to compute the memory address by indexing into the linear memory, and another performing the access, between which memory.grow may have invalidated the address.

Are there any strategies for resolving the race between memory.grow and memory accesses, short of having something like a rlock for memory accesses and wlock for memory.grow with respect to the memory base (that seems prohibitive)? Anyone know how cranelift or v8 handle this?

**Comment by conrad-watt** [comment]
This is something I only have a second-hand understanding of, so I'll answer as best I can in the hope of invoking [Cunningham's Law](https://en.wiktionary.org/wiki/Cunningham%27s_Law).

Implementing `memory.grow` using a relocation strategy is very difficult if the memory is shared. I'm not aware of any real implementation that does this. I don't have a full picture in my head of how this strategy could work, but it might be possible through something like the following (I'll stick to Windows [terminology](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc) here):

- when `memory.grow` is executed, stop the world (interrupt all threads)
- relocate the memory
- decommit the old location
- commit the old location with permission `PAGE_NOACCESS` (it won't take up physical memory until first access)
- restart the world
- when a protection fault occurs due to an access to the old location (e.g. because the thread computed the memory address before the world was stopped), catch it and fix up execution of that thread with the new address

Essentially every implementation I'm aware of preallocates memory, but uses OS trickery to keep memory beyond the "Wasm bound" out of physical memory until it's actually grown into. This avoids needing to stop the world as above.

**Comment by anuraaga** [comment]
> Essentially every implementation I'm aware of preallocates memory, but uses OS trickery to keep (most) memory beyond the "Wasm bound" out of physical memory until it's actually grown into.

Thanks, I thought this might be the case, especially with the requirement for maximum pages for shared memory. Not an expert so I'll have to reread the flags / understand how to achieve this presumably with mmap!

**Comment by anuraaga** [comment]
Thanks again @conrad-watt the hint to use mmap worked out well
