### ISSUE TITLE
Is wake count = 0 useful?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/threads#23]
Is it ever semantically useful for a caller of `wake` to pass `0`?  If "no", then I think we could simplify `wake` a bit by having `wake count` be interpreted as unsigned with `0` meaning "wake all waiters".  For reference, [`Atomics.wake`](https://tc39.github.io/ecma262/#sec-atomics.wake) lets you pass `+∞` or `undefined` to wake all waiters.

**Comment by lars-t-hansen** [comment]
I think it is semantically useful for a caller of wake to pass 0, it could be a natural consequence of algorithms that track how many waiters there are.  You can argue that the check for that special case can be hoisted into the caller, but that seems like a fiddlier API to me, without clear benefits.

I think passing a negative number for "all" is OK, though I'd probably prefer for it to be a specific negative number rather than any negative number.

Another option is to reserve 0xFFFFFFFF for "all" and make the wake count unsigned.

**Comment by rossberg-chromium** [comment]
I'd avoid sentinel values, especially ones that introduce sharp discontinuities in the value range -- that's always a source for subtle bugs; 0 in particular, for the reasons @lars-t-hansen mentions.

**Comment by lukewagner** [comment]
Ah, right; passing 0 could just fall out of a general algorithm and so we'd just be making more work for caller / creating bugs.  I guess what bugged me is seeing there be 3 cases when it seemed like there should be 2, but I guess that's just an artifact of the prose description; the 0 and >0 cases aren't really separate.

No strong feeling on unsigned/UINT32_MAX option (although technically, it allows waking INT32_MAX more waiters in a single call ;-)  I'll close the issue for now but anyone feel free to propose this.

**Comment by binji** [comment]
> the 0 and >0 cases aren't really separate.

I just noticed that myself. :-)

> No strong feeling on unsigned/UINT32_MAX option...

I figured it was nicer to have a check for sign rather than specific value. Probably doesn't really make a difference for perf, but seemed simpler.

**Comment by jfbastien** [comment]
I'd rather have a separate opcode than a sentinel.
