### ISSUE TITLE
Embedder suspension

### ISSUE THREAD

**Issue by MikeHolman** [WebAssembly/threads#25]
>The embedder is also permitted to suspend or wake an agent. A suspended agent can be woken by the embedder or the wake.

Is this implying that wake can wake a thread suspended by the embedder? I am guessing not, but it isn't totally clear to me.

**Comment by lars-t-hansen** [comment]
I think part of the confusion here is that "embedder" can mean either the browser or the surrounding JS code (assuming a web setting).  This also came up in issue #21 and I think it needs to be cleaned up properly.  In the JS spec, the embedding *cannot* suspend a subset of the agents in a cluster; it suspends all of them, or none, and none of them can then be woken by any wake call, since there's no agent to perform such a call.

The wasm spec is in a tricky situation in that wasm is technically independent of the web and JS.  Yet, in the short term, I think that it would be most efficient to simply point to the JS spec as the truth for both agent behavior and memory model, and then note any additional facts that pertain to wasm.

**Comment by binji** [comment]
> The wasm spec is in a tricky situation in that wasm is technically independent of the web and JS. Yet, in the short term, I think that it would be most efficient to simply point to the JS spec as the truth for both agent behavior and memory model, and then note any additional facts that pertain to wasm.

Agreed, it seems that my selective copying of the ECMAScript spec as a starting point has just made things more confusing. :-)

It's also worth pointing out that this is basically what we agreed to in the meeting for the memory model already, so doing the same for agents and wake/wait semantics seems reasonable too.

**Comment by binji** [comment]
Closing assuming this is clarified by #42. If not, please re-open.
